version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"        # ganti ke "5433:5432" kalau 5432 sudah dipakai
    volumes:
      - dbdata:/var/lib/postgresql/data

  horilla:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./:/app
      - ./media:/app/media
      - ./static:/app/static
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: >
      bash -lc "
      apt-get update &&
      apt-get install -y --no-install-recommends build-essential libpq-dev &&
      pip install --no-cache-dir -r requirements.txt &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "

volumes:
  dbdata:
